### ISSUE TITLE
Reference Not Defined? Not Sure How To Get This Working

### ISSUE THREAD

**Issue by alteredorange** [samuelgozi/firebase-storage-lite#2]
Hello! This looks awesome, just implemented your Auth package, and so far so good! I'm trying to get this working, but not sure I'm doing it right. Basically trying to make a storage object to work with, but when I do this:
`import Reference from 'firestore-storage-lite';
export const storage = new Reference(config.storageBucket);`
I get a "Reference is not defined", Rollup says it's missin ga global variable name. Is there any other setup? Would you be able to post a dummy example of setting config and uploading a file? Thanks for the help, can't wait to try it out!

**Comment by samuelgozi** [comment]
Hi Bob, thank you for opening an issue.
I tried to reproduce your error, but It seems to work for me.
Can you provide a little bit more info?

Specifically, if you can please comment with your rollup config, or even better if you can, a repository(or even a zip file) with minimal stuff needed to reproduce the error.

The error doesn't seem to originate from the library, so I'm guessing it has something to do with the build process.

And if you get any other errors in the console, that could be helpful too.

**Comment by samuelgozi** [comment]
Mmmm... After looking at your code again, I spotted a typo, which exists in the README file again, so it's my fault.

The name of the Library is `firebase-storage-lite` and not `firestore-storage-lite`(Fire**base** not Fire**store**).

Im sorry, I always confuse them because I write them so much 😅...

That should solve the issue.
Please comment if it does, so I can close this.

**Comment by alteredorange** [comment]
Haha, great thanks! That worked, now on to uploading!

**Comment by samuelgozi** [comment]
Feel free to ask/suggest anything else.
