### ISSUE TITLE
Progress Indicators

### ISSUE THREAD

**Issue by alteredorange** [samuelgozi/firebase-storage-lite#3]
Alright, I got some images uploaded!

So it looks like no progress tracking yet, correct? Any hints for large files, or just keep showing a loading symbol? 

` var uploadTask = testRef.put(blob);
          uploadTask.start(
function(error) {
console.log(error);
}, function() {
console.log("upload complete!");
}
);`

That upload function doesn't log anything, seems to work the same as uploadTaks.start(), so I'm guessing we can't pass functions. How do you retrieve the metadata from the promise? Thanks for the help, I love how I can use these libraries without a bajillion errors like the official ones!

**Comment by samuelgozi** [comment]
You asked a few questions so if I miss anything feel free to point it out.
1. Indicators - It's tricky. At the correct state of the FetchAPI, it's impossible to get any upload indication. However, when files are larger than 50MB(some calculations suggested that with today's internet speed this might be a good choice) the upload is done with multiple requests, so I might be able to use that to return upload indication. It will change the API though(it's still in Beta so I don't follow semantic versioning yet).
2. Yes, the upload currently doesn't log anything. It only throws when it fails. I didn't add functionality because I didn't have any good idea, about how the API should look, but I think I've got an idea now.
3. You asked about retrieving metadata from the promise. What kind of metadata are you asking about? If it's regarding the upload, then it currently doesn't offer any.

I'll be honest, I didn't work on this lib for a while, mainly because it is used by far fewer people than the other ones, so I didn't really have any pressure to do so. So I appreciate your questions and suggestions!

I will try to find some time in the next few days to add some way to track upload progress, and refine the API. Hopefully, it will solve most of the issues you mentioned, however it might make compatibility with older browsers a little hard.

I will update soon.

**Comment by alteredorange** [comment]
Hi Samuel,
Thanks I appreciate all the answers, sorry for all the questions!  Yeah one nice thing the original api has is the progress snapshot:

     uploadTask.on(
             "state_changed",
             function(snapshot) {
               // Observe state change events such as progress, pause, and resume
               // Get task progress, including the number of bytes uploaded and the total number of bytes    to be uploaded
               var progress =
                 (snapshot.bytesTransferred / snapshot.totalBytes) * 100;
               console.log("Upload is " + progress + "% done");
             },

I thought the upload returned the metadata because of the docs:

`UploadTask(instance).start()

Start the Upload process.
Returns

A Promise that resolves when the upload is complete, and returns the metadata of the newly uploaded object.`

But it's not a big issue, I already have the path and everything.  Thanks for taking the time, have a great rest of the week!

**Comment by samuelgozi** [comment]
I'm reopening the issue because I do think that it is an important feature.

**Comment by samuelgozi** [comment]
I just published some changes that address this issue.
It still needs some improvement(It still lacks "abort" functionality), but the API is much better in my opinion.
Please note that this are **breaking changes**! This shouldn't come as a surprise since this is still a beta.

The main change is that now when calling the `put` method on a reference, it will return an `UploadTask` that will start to upload immediately. The `UploadTask` now implements the `Promise` protocol, so you can use methods like `then`, `catch`, and `finally`, and is also an async iterator.
So you can iterate over it to get progress updates.

Example of using as a promise:

```js
const upload = ref.put(blob); // returns an instance of UploadTask.

// Will log the metadata when the upload is finished.
upload.then(meta => {
	console.log(meta);
});

// Handle errors.
upload.catch(e => {
	console.error(meta);
});

// Will be run when the promise resolves.
upload.finally(() => {
	console.log('done or failed');
});
```

Using as an async iterator:

```js
for await (const { offset, total } of ref.put(blob)) {
	console.log((offset / total) * 100);
}

// Will log percentage
// 0
// 12
// 24
// 36
// 48
// ... and so on.
```
Please let me know what you think.

**Comment by alteredorange** [comment]
Great work, you're quick! Everything seems to be working just great!
